Repository open-services-group/byon, pull requests merged in 2022-03, with the labels that each got.

#29 feat: Add a basic make test
  Makefile
Labels: lgtm, size/M, approved

#35 Add OptaPy and R images in the test
  Makefile
Labels: lgtm, approved, size/S, ok-to-test

#24 Updated Readme
  README.md
Labels: lgtm, size/M, approved

#36 added OS-Climate image to test
  Makefile
Labels: lgtm, approved, size/XS

#37 make oindrillac and tumido approvers
  OWNERS
Labels: approved, size/XS
